{% set name = "dlfcn-win32" %}
{% set version = "19" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dlfcn-win32/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: fe4dd5f34b4dad759c4e137003310256b8ba2a747c181402aa194170aba78899

build:
  number: 0
  skip: true  # [not win or vc<14]
  run_exports:
    - {{ pin_subpackage('dlfcn-win32', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake

test:
  commands:
    - if exist %PREFIX%\\Library\\share\\dlfcn-win32\\dlfcn-win32-config.cmake (exit 0) else (exit 1)

about:
  home: https://github.com/dlfcn-win32/dlfcn-win32
  license: LGPL-2.1
  license_file: COPYING
  summary: dlfcn-win32 is an implementation of dlfcn for Windows.

extra:
  recipe-maintainers:
    - seanyen
    - traversaro
