{% set name = "dlfcn-win32" %}
{% set version = "1.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dlfcn-win32/dlfcn-win32/archive/v{{ version }}.tar.gz
  sha256: f61a874bc9163ab488accb364fd681d109870c86e8071f4710cbcdcbaf9f2565

build:
  number: 0
  skip: true  # [not win]
  run_exports:
    - {{ pin_subpackage('dlfcn-win32', max_pin='x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake

test:
  commands:
    - if exist %PREFIX%\\Library\\share\\dlfcn-win32\\dlfcn-win32-config.cmake (exit 0) else (exit 1)

about:
  home: https://github.com/dlfcn-win32/dlfcn-win32
  license: MIT
  license_file: COPYING
  summary: 'dlfcn-win32 is an implementation of dlfcn for Windows.'

extra:
  recipe-maintainers:
    - seanyen
    - traversaro
